version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 8000:80
      - 5000:5000
    environment:
      PG_HOST: ${POSTGRES_HOST}
      PG_DB: ${POSTGRES_DB}
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    volumes:
      - ./app:/app
      - ./Moscow:/etc/localtime

  db:
    image: postgres:12
    environment:
      PGTZ: 'Europe/Moscow'
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../cul-blog-db:/var/lib/postgresql/data
      - ./Moscow:/etc/localtime
